-- 3. Desarrollar un bloque PL/SQL que permita obtener
--  información sobre los clientes fijos y esporádicos
-- u ocasionales (son los clientes que efectúan visitas 
-- ocasionalmente al supermercado), que efectuaron
-- transacciones en los últimos 3 meses (ideal que el
-- tiempo sea variable).
-- Por ejemplo:

-- *********************** LISTADO DE CLIENTES FIJOS *****************************
-- 1) Nombre: Juan Apellido Paterno: Pérez Apellido Materno: Sa Fono: 123
-- 2) Nombre: María Apellido Paterno: Salas Apellido Materno: Gómez Fono: 456
-- 3) Nombre: Emilio Apellido Paterno: Laguna Apellido Materno: Flores Fono: 123
-- ***********************LISTADO DE CLIENTES ESPORÁDICOS************************
-- 1) Nombre: Luisa Apellido Paterno: Alcón Apellido Materno: Quezada Fono: 123
-- 2) Nombre: Erigberto Apellido Paterno: López Apellido Materno: Laguna Fono: 416
-- 3) Nombre: Juan Apellido Paterno: Poma Apellido Materno: Quispe Fono: 475
-- 4) Nombre: Freddy Apellido Paterno: Luna Apellido Materno: Montoya Fono: 482